app = "niya-jewels-backend"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  protocol = "tcp"
  internal_port = 9000
  ports = [{ port = 80, handlers = ["http"] }, { port = 443, handlers = ["http", "tls"] }]
